### ISSUE TITLE
More details for reproduction of figure 3

### ISSUE THREAD

**Issue by zhan8855** [OmicsML/CellPLM#1]
Hi,

Thank you for your awesome work!

Could you please release more details in reproduction of figure 3 (e.g. code of scGPT for zero-shot setting  : )

Thank you very much in advance!

**Comment by wehos** [comment]
Hi. For scGPT, we followed their github repo to generate cell embeddings from GSE155468 dataset and visualized it with scanpy.  For CellPLM, please refer to the [latest tutorial](https://github.com/OmicsML/CellPLM/blob/c684c93985abb3dc558e8a4d8a491a53c2348a83/tutorials/cell_embedding.ipynb), thanks!

**Comment by zhan8855** [comment]
Great! But it seems that scGPT did not release the code for zero-shot clustering. Could you please provide more details on how to retrieve the embeddings for visualization from scGPT? Thank you very much!

**Comment by wehos** [comment]
Integration is equivalent to cell clustering across datasets. You may retrieve the embeddings in the same way as [integration]( https://github.com/bowang-lab/scGPT/blob/main/examples/finetune_integration.py). For zero-shot evaluation, just skip the training (a.k.a, fine-tuning).

**Comment by zhan8855** [comment]
Thank you so much for your valuable information!
