### ISSUE TITLE
Request for Update on Dataset Details described in Table 6

### ISSUE THREAD

**Issue by litxiaoyao** [OmicsML/CellPLM#15]
![屏幕截图 2024-07-10 153204](https://github.com/OmicsML/CellPLM/assets/68361174/fdca3950-088e-43da-81c9-806441384acd)

**Comment by litxiaoyao** [comment]
CELLxGENE census  version 15 May 2023 has 33M cells, however you said only used 11M, what's the difference?
![屏幕截图 2024-07-10 153342](https://github.com/OmicsML/CellPLM/assets/68361174/e45a340f-bd8c-419b-a9ea-8aa6e84843b4)

thanks

**Comment by lemousehunter** [comment]
Hi, I'm wondering if the links for the dataset / its subsets that have been used for pretraining have been included in this repo. And if so, could anyone help to ping it here please :) Thanks!
