### ISSUE TITLE
Public Training and Fine-tuning Pipeline

### ISSUE THREAD

**Issue by WhenMelancholy** [OmicsML/CellPLM#2]
Hello, I noticed that the current code seems to lack the relevant sections for retraining or fine-tuning CellPLM. Do you have any plans to release this part in the future? This includes the training fine-tuning pipeline and dataset handling procedures.
Thank you for your effort.

**Comment by wehos** [comment]
Hi! The `fit` functions in [pipeline](https://github.com/OmicsML/CellPLM/tree/main/CellPLM/pipeline) module is for tine-tuning purposes. For example, [here](https://github.com/OmicsML/CellPLM/blob/24f1e817383eaa2694dd14d904cd7c16dcbc2b64/CellPLM/pipeline/cell_type_annotation.py#L107C8-L107C8). For complete instructions, please refer to our tutorials.

**Comment by WhenMelancholy** [comment]
Thank you for your prompt reply, and I sincerely apologize for not noticing the details related to fine-tuning earlier. May I inquire if you have any plans to release the training code? I greatly appreciate your assistance!

**Comment by wehos** [comment]
Hi, unfortunately, we cannot release the pretrain codes right now due to IP concerns. We notice that scGPT did not release their pretrain codes as well. We might be able to release our pretrain codes in the future.
