### ISSUE TITLE
Request for Update on Dataset Details

### ISSUE THREAD

**Issue by mufanq** [OmicsML/CellPLM#5]
Hello, I noticed that the paper mentioned updates on the details of the training dataset would be made available in the GitHub repository. May I ask if there are plans to update this part? For instance, which parts of the HTCA HCA GEO dataset were used? Thank you!

**Comment by wehos** [comment]
Thank you for your reminder. I will work on this issue and will keep you posted.

**Comment by wehos** [comment]
Hi,

I did double check that the detailed dataset list was provided in the supplementary file in our ICLR submission [here](https://openreview.net/attachment?id=BKXvPDekud&name=supplementary_material) in Table 6 on [openreview](https://openreview.net/forum?id=BKXvPDekud).

Note that in Septemeber (right after the submission) we have trained a new version of the model with [CellxGene Census LTS 2023-05-15](https://chanzuckerberg.github.io/cellxgene-census/cellxgene_census_docsite_data_release_info.html#lts-2023-05-15). Therefore, any checkpoints after September will be based on this data sources.

**Comment by WhenMelancholy** [comment]
Thank you for your help!
