### ISSUE TITLE
Cannot open spatial h5ad files

### ISSUE THREAD

**Issue by WhirlFirst** [OmicsML/CellPLM#7]
Hi,

Thank you for providing the data files. When I tried to open the HumanLiverCancerPatient2_filtered_ensg.h5ad file downloaded from Dropbox, I got an error:
```
OSError: Can't synchronously read data (filter returned failure during read)
Error raised while reading key '/obs/fov' of <class 'h5py._hl.dataset.Dataset'> to /
```
I don't know whether it is caused by the different versions or if it means the file is corrupted.  Could you give me more information or test to read it on your computer?

Thanks in advance.

**Comment by wehos** [comment]
Please make sure you installed `hdf5plugin` (via `pip install hdf5plugin`) and import it before loading the data. This was included in the tutorial codes.

I don't have other ideas about this issue. I cannot reproduce it and I just successfully loaded the data on my local laptop.

**Comment by WhirlFirst** [comment]
> Please make sure you installed `hdf5plugin` (via `pip install hdf5plugin`) and import it before loading the data. This was included in the tutorial codes.
> 
> 
> 
> I don't have other ideas about this issue. I cannot reproduce it and I just successfully loaded the data on my local laptop.

Thanks for your help. I thought it was an anndata file and read it by the scanpy function. I will use this package. Thanks
